name: newcairo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  awesome_dialog: ^3.1.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_svg: ^2.0.5
  get: ^4.6.1
  get_it: ^7.2.0
  loading_animation_widget: ^1.1.0+1
  mime: ^1.0.2
  path_provider: ^2.0.1
  provider: ^6.0.1
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  webview_flutter: ^2.0.4
#  flip_card: ^0.6.0
#  credit_card_type_detector: ^2.0.0
#  sign_in_with_apple: ^4.1.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900
